In [ ]:
import numpy as np
import sys
s=list(range(1000))
print(sys.getsizeof(1000))
print(sys.getsizeof(1000)*len(s))

a=np.arange(1000)
print(a.itemsize)
print(a.size*a.itemsize)


28
28000
8
8000


In [ ]:
import time
t1=time.time()
x=range(1000)
y=range(1000)
z=[x[i]+y[i] for i in range(len(x))]
print(time.time()-t1)



0.0007736682891845703


In [ ]:
t1=time.time()
x=np.arange(1000)
y=np.arange(1000)
z=x+y # Convenient
print(time.time()-t1)

0.00022459030151367188


In [ ]:
# Creating a Numpy Array


In [ ]:
a=np.array([1,2,3,4,5]) # one dimensional array
print(a)

[1 2 3 4 5]


In [ ]:
aa=np.array([[1,2,3],[4,5,6], [7,8,9]])  # two dimensional array
print(aa)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
aaa=np.array([[(1,2,3),(4,5,6),(7,8,9)],[(11,12,13),(14,15,16),(17,18,19)],[(21,22,23),(24,25,26),(27,28,29)]])  # three dimensional array
print(aaa)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
print(aaa.ndim)
print(aaa.shape)

print(aa.ndim)

3
(3, 3, 3)
2


In [ ]:
print(aaa.ndim) # dimension of array
print(aaa.itemsize)  # size of each element
print(aaa.dtype)  # datatye of element in array
print(aaa.size) # total no. of elements


3
8
int64
27


In [ ]:
# Accessing element of an array

In [ ]:
a=np.array([1,2,3,4,5])
print(a)  
print(a[1])

[1 2 3 4 5]
2


In [ ]:
print(aa)
print(aa[1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [ ]:
print(aa)
print(aa[1,1])   # using comma

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [ ]:
print(aaa)
print(aaa[1,1,1]) 

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
15


In [ ]:
# Reshaping an array in Numpy


In [ ]:
one=np.arange(1,26)
print(one)
two=one.reshape(5,5)   #reshape() convert from one to two dimension
print(two)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
Newone=two.reshape(1,25)
print(Newone)
print(Newone.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]]
(1, 25)


In [ ]:
Newone=two.reshape(-1)
print(Newone)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [ ]:
#ravel() 

In [ ]:
Newone=np.ravel(two)  #ravel() is a builit in function to convert from 2D to 1D
print(Newone)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [ ]:
#Slicing in Numpy

In [ ]:
print(two)
subtwo=two[1:3,1:4]
print(subtwo)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]]


In [ ]:
print(two)
subtwo=two[1:,1:]         # row start is 1, but end is not given
print(subtwo)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# Built in methods to create Numpy Array
1. arange()
2. zeros()
3. ones()
4. eye()
5. Linspace()
6. Random Array -  rand(), randn(), randint()

In [ ]:
s=np.arange(1,101)
print(s)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
s=np.zeros(5, dtype=np.int32)
print(s)

[0 0 0 0 0]


In [ ]:
s=np.zeros([5,3])
print(s)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
s=np.zeros([2,5,5])
print(s)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
s=np.ones(5, dtype=np.int32)
print(s)

[1 1 1 1 1]


In [ ]:
s=np.ones([3,3])
print(s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
s=np.ones((2,3,3))
print(s)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
s=np.ones((2,3,3),dtype=int)
print(s)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
s=np.ones((2,3,3),dtype=np.int32)
print(s)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
#eye - Identical Matrix

In [ ]:
s=np.eye(3,3,dtype=int)
print(s)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
s=np.eye(3,3,k=1, dtype=int)
print(s)

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [ ]:
s=np.eye(3,3,k=-2,dtype=int)
print(s)

[[0 0 0]
 [0 0 0]
 [1 0 0]]


In [ ]:
#linspace()

In [ ]:
l=np.linspace(1,10,15)  #start,end, no.of elements
print(l)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [ ]:
l=np.linspace(1,10,5)  #start,end, no.of elements
print(l)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
l=np.linspace(1,10,15,retstep=True)  #start,end, no.of elements
print(l)

(array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]), 0.6428571428571429)


In [ ]:
l=np.linspace(1,10,30,retstep=True)  #start,end, no.of elements
print(l)

(array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ]), 0.3103448275862069)


In [ ]:
# Random Array 

In [ ]:
#rand()

In [ ]:
ra=np.random.rand(50)   # values between 0 and 1
print(ra)

[0.35954429 0.27447662 0.84852136 0.36701514 0.91287822 0.29822642
 0.68110139 0.13736674 0.18211267 0.1001592  0.5778922  0.76522315
 0.02858771 0.99812132 0.82627939 0.26842818 0.96711795 0.85036793
 0.92292769 0.40520318 0.08500374 0.78486051 0.95129694 0.7327043
 0.2162757  0.88037796 0.09948412 0.87215656 0.62228712 0.1572027
 0.42578428 0.58826464 0.86954768 0.36600157 0.45991871 0.66817305
 0.36127638 0.59694518 0.40467254 0.95801069 0.29768017 0.42610737
 0.60710233 0.01195667 0.77080362 0.06658959 0.41842445 0.99341986
 0.51628092 0.61204892]


In [ ]:
ra=np.random.rand(5,3)   # values between 0 and 1
print(ra)

[[0.1379976  0.76051164 0.5048168 ]
 [0.48743683 0.81710557 0.03064068]
 [0.89545174 0.58816847 0.5092785 ]
 [0.99126136 0.11973923 0.46593789]
 [0.99963415 0.60818867 0.22630446]]


In [ ]:
#randn()

In [ ]:
ra=np.random.randn(5)   # Normal (Gaussian) distribution of mean 0 and variance 1
print(ra)

[ 0.2883826  -0.83929114  0.27953606  2.32718889  1.54717343]


In [ ]:
ra=np.random.randn(5,3)   # Normal (Gaussian) distribution of mean 0 and variance 1
print(ra)

[[-2.73110438  0.62754862  0.37358318]
 [ 0.24006317 -2.40878709  0.30157705]
 [-0.85687559  1.23090137 -0.01831022]
 [ 2.94253819 -1.25160009 -1.11231997]
 [-1.50543    -0.17826834  0.29843822]]


In [ ]:
# randint()

In [ ]:
ra=np.random.randint(100)   # Integer value randomly 
print(ra)

50


In [ ]:
ra=np.random.randint(10,100)   # Integer value randomly 
print(ra)

55


In [ ]:
ra=np.random.randint(10,100,5)   # Integer value randomly 
print(ra)

[88 17 77 33 63]


In [ ]:
# Arithmetic Operations

In [ ]:
a=np.array([10,20,30,40,50]) 
b=np.array([5,10,15,20,25])
print("addition", a+b)
print("subtraction", a-b)
print("multiplication", a*b)
print("division", a/b)
print("floor division", a//b)
print("modulo", a%b)

addition [15 30 45 60 75]
subtraction [ 5 10 15 20 25]
multiplication [  50  200  450  800 1250]
division [2. 2. 2. 2. 2.]
floor division [2 2 2 2 2]
modulo [0 0 0 0 0]


In [ ]:
# Broadcasting

In [ ]:
a=np.array([10,20,30,40,50]) # 50 will be added with each element in an array
b=a+50
print(b)

[ 60  70  80  90 100]


In [ ]:
# Mathematical Functions
1. sqrt()
2. exp()
3. sin()
4. cos()
5. sum()
6. log()
7. std()
8. max()
9. min()
10. argmax()
11. argmin()


In [ ]:
a=100
print(np.sqrt(a))
print(int(np.sqrt(a)))

10.0
10


In [ ]:
a=np.array([10,20,30,40,50]) 
print(np.sqrt(a))


[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [ ]:
a=np.array([10,20,30,40,50]) 
print(np.exp(a))

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [ ]:
a=np.array([10,20,30,40,50]) 
print("sine", np.sin(a))
print("cos", np.cos(a))
print("log", np.log(a))
print("std", np.std(a))
print("sum",np.sum(a))


sine [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
cos [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
log [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
std 14.142135623730951
sum 150


In [ ]:
a=np.array([[10,20,30],[40,50,60]])
print("sum of 2D", a.sum()) 

sum of 2D 210


In [ ]:
print(a)
print("sum of 2D", a.sum(axis=0))  # sum of all the columns

[[10 20 30]
 [40 50 60]]
sum of 2D [50 70 90]


In [ ]:
print(a) 
print("sum of 2D", a.sum(axis=1)) # sum of all the rows

[[10 20 30]
 [40 50 60]]
sum of 2D [ 60 150]


In [ ]:
print(a) 
print("Maximum", a.max())

[[10 20 30]
 [40 50 60]]
Maximum 60


In [ ]:
print(a) 
print("Minimum", a.min())

[[10 20 30]
 [40 50 60]]
Minimim 10


In [ ]:
print(a) 
print("Indix - Maximum :", a.argmax())

[[10 20 30]
 [40 50 60]]
Indix - Maximum : 5


In [ ]:
print(a) 
print("Index - Minimum :", a.argmin())

[[10 20 30]
 [40 50 60]]
Index - Minimum : 0
